# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "activesupport", require: false
gem 'backports', require: false
gem 'deepsort', require: false
gem "nokogiri", require: false
gem "rake"
gem 'pycall', require: false
